#!/bin/csh -f

cd $PWD

rm .cs*

xterm -T "BRIDGE cs1" -iconic -e ./bridge cs1 8 &
xterm -T "BRIDGE cs2" -iconic -e ./bridge cs2 8 &
xterm -T "BRIDGE cs3" -iconic -e ./bridge cs3 8 &
sleep 5
xterm -T "Host A" -e ./station -no ifaces/ifaces.a rtables/rtable.a hosts &
sleep 1
xterm -T "host B" -e ./station -no ifaces/ifaces.b rtables/rtable.b hosts &
sleep 1
xterm -T "host C" -e ./station -no ifaces/ifaces.c rtables/rtable.c hosts &
sleep 1
xterm -T "host D" -e ./station -no ifaces/ifaces.d rtables/rtable.d hosts &
sleep 1
xterm -T "host E" -e ./station -no ifaces/ifaces.e rtables/rtable.e hosts &
sleep 5
xterm -T "Router r1" -iconic -e ./station -route ifaces/ifaces.r1 rtables/rtable.r1 hosts &
xterm -T "Router r2" -iconic -e ./station -route ifaces/ifaces.r2 rtables/rtable.r2 hosts &


